### ISSUE TITLE
Valeur de OAUTH_OC_CLIENT_SECRET

### ISSUE THREAD

**Issue by Spheerys** [XenoX/my-oc#8]
J'essaie de suivre la procédure d’installation mais je coince sur la récupération de la clé OAUTH_OC_CLIENT_SECRET
La console JS me donne comme résultat à la requête App.api.anonymous.client_secret que le chiffre "1"
Est-ce normal ?
L'API a-t-elle évoluée récemment ?

**Comment by XenoX** [comment]
Le client_secret est "1" pour tout le monde, donc oui c'est normal :)
